---
language: node_js
dist: trusty
sudo: false
node_js:
  - "6"
  - "7"
env:
  matrix:
    - RUST=stable
    - RUST=beta
    - RUST=nightly
  global:
    - "PATH=$PATH:$HOME/rust/bin"
matrix:
  allow_failures:
    - env: RUST=nightly
    - node_js: "7"
install: echo Running npm install AFTER rustup
before_script:
  - mkdir $HOME/rust
  - "curl -sL https://static.rust-lang.org/rustup.sh -o ~/rustup.sh"
  - "sh ~/rustup.sh --prefix=~/rust --spec=$RUST -y --disable-sudo"
  - rustc --version
  - cargo --version
  - npm install
after_script:
  - cd native
  - cargo test -p post
  - cargo test -p list
