---
language: node_js
dist: trusty
sudo: false
node_js:
  - "8"
  - "9"
env:
  matrix:
    - RUST=stable
    - RUST=beta
    - RUST=nightly
  global:
    - "PATH=$PATH:$HOME/rust/bin"
matrix:
  fast_finish: true
  allow_failures:
    - env: RUST=nightly
cache:
  directories:
    - $HOME/.npm
    - $HOME/.cargo
install: echo Running npm install AFTER rustup
before_script:
  - mkdir $HOME/rust
  - "curl -sL https://static.rust-lang.org/rustup.sh -o ~/rustup.sh"
  - "sh ~/rustup.sh --prefix=~/rust --spec=$RUST -y --disable-sudo"
  - rustc --version
  - cargo --version
  - npm install --global npm@^5
  - npm install
script:
  - npm test
  - cd native
  - cargo check
  - cargo test -p post
  - cargo test -p list
