---
language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - nvm install lts
  - npm install
script:
  - cd native
  - cargo test --all
  - cd ..
  - npm run install
  - npm test
