---
language: node_js
dist: trusty
sudo: false
node_js: 10
cache:
  directories:
    - $HOME/.npm
    - $HOME/.cargo
install: echo Running npm install AFTER rustup
before_script:
  - "curl -sL https://static.rust-lang.org/rustup.sh -o ~/rustup.sh"
  - "sh ~/rustup.sh -y"
  - "source $HOME/.cargo/env"
  - rustc --version
  - cargo --version
  - npm ci
script:
  - npm test
  - cd native
  - cargo check
  - cargo test -p post
  - cargo test -p list
