source 'https://rubygems.org'
ruby '2.1.2'

gem 'activesupport', require: false
gem 'asciidoctor'
gem 'creole'
gem 'foreman', group: :development
gem 'haml'
gem 'liquid'
gem 'markaby'
gem 'memoist'
gem 'numbers_and_words'
gem 'org-ruby'
gem 'puma'
gem 'redcarpet'
gem 'RedCloth'
gem 'rugged', '0.19.0'
gem 'sanitize'
gem 'sinatra'
gem 'slim'
#gem 'tumblr_client'
gem 'typhoeus'
gem 'wikicloth'
