[package]
name = "post"
version = "0.2.0"
workspace = ".."
edition = "2018"

[dependencies]
chrono = "0.4.0"
crowbook-text-processing = "0.2.6"
iso8601 = "0.3.0"
lazy_static = "1.3.0"
num-traits = "0.2.6"
pulldown-cmark = "0.4.1"
regex = "1.1.5"
yaml-rust = "0.4.3"
