[package]
name = "post"
version = "0.1.0"
workspace = ".."

[dependencies]
chrono = "0.3.1"
crowbook-text-processing = "0.2.6"
iso8601 = "0.1.1"
lazy_static = "0.2.8"
num-traits = "0.1.37"
pulldown-cmark = "0.0.14"
regex = "0.2.2"
yaml-rust = "0.3.5"
