[package]
name = "list"
version = "0.1.0"
workspace = ".."

[dependencies]
post = { path = "../post" }

chrono = "0.3.0"
lazy_static = "0.2.2"
log = "0.3.6"
regex = "0.2.1"
time = "0.1.36"
walkdir = "1.0.7"
yaml-rust = "0.3.5"
